name: worker_manager
description: Executor allows you to create a queue of tasks for isolate pool
version: 2.0.5
author: Daniil Surnin <dsrenesanse@gmail.com>
homepage: https://github.com/Renesanse/worker_manager

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.3.0
  uuid: ^2.0.2
  stream_transform: ^0.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
