name: worker_manager
description: wrapper an isolate
version: 0.2.3
author: Daniil Surnin <dsrenesanse@gmail.com>
homepage: https://github.com/Renesanse/worker_manager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: