name: worker_manager
description: Executor allows you to create a queue of tasks for threadpool of isolates
version: 1.0.6
author: Daniil Surnin <dsrenesanse@gmail.com>
homepage: https://github.com/Renesanse/worker_manager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: