name: deptest
description: A new Flutter project.
version: 0.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  flutter_datetime_picker:
  sticky_headers:
  flutter_slidable: 0.4.7
  tuple:

  built_value:
  built_collection:
  built_redux:
  flutter_built_redux:
  built_redux_rx:
  shared_preferences:
  reselect:
  async:
  flutter_webview_plugin:
  memoize:
  collection:
  meta:
  path_drawing:
  vector_math:
  flutter_swiper:
  local_auth: 0.4.0+1
  flip_panel:
  dioc:
  flutter_reorderable_list:
  flutter_sidekick:
  url_launcher:
  google_sign_in:
  firebase_auth:
  firebase_core:
  cloud_firestore:
  firebase_storage:
  firebase_remote_config:
  uuid:
  image_picker:
  auto_size_text:
  device_info:
  video_player: 0.10.0+8
  package_info:
  flutter_full_pdf_viewer:
  path_provider:
  firebase_messaging:
  flutter_svg:
  location:
  connectivity:
  auto_orientation:
  keyboard_visibility:
  carousel_slider:
  dotted_border:
  screen:
  stream_transform: ^0.0.19
  flutter_inappbrowser: ^1.2.1
  provider:
  flare_flutter:

  flutter_matomo:
    git:
      url: https://vcs.app-ses.com/scm/~sobol/flutter_matomo.git

  flutter_statusbar_manager:
    git:
      url: https://vcs.app-ses.com/scm/mob/flutter_statusbar_manager.git

  #  flare_flutter:
  #  #   path: ../flare_flutter


  webview_flutter:
  native_device_orientation:
  configurable_expansion_tile:
  pull_to_refresh:
  flutter_sticky_header:
  flutter_easyrefresh: ^1.2.7
  flutter_masked_text: ^0.8.0
  flutter_widgets: 0.1.6-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  junitreport:
  intl_translation:

  build:
#  build_config:
  built_value_generator:
  build_runner:
#  dartdoc:
#  mockito:
#  redux_dev_tools:
#  socketcluster_client:

  dioc_generator:
#  pedantic:
  # redux_remote_devtools:
  #   git:
  #     url: https://github.com/tdesc/dart-redux-remote-devtools.git
dependency_overrides:
#  intl: 0.16.0
  analyzer: 0.36.4

flutter:
  uses-material-design: true
